<?php
/**
 * Rendered blocks with per-render generated CSS.
 *
 * WordPress generates some block-support CSS at render time — layout
 * container rules (flex/grid/gap), element link/button colors, duotone
 * filters — and prints it in a <style> tag on its own frontend. That CSS
 * never reaches REST responses, so headless frontends rendering
 * `content.rendered` get the generated class names without their rules.
 *
 * This module renders the post content during the REST request and captures
 * the CSS generated by that same render. HTML and CSS must come from one
 * render because generated container class names (wp_unique_prefixed_id)
 * are not stable across renders.
 *
 * @package HeadlessBlockStyles
 */

namespace HeadlessBlockStyles\Render;

use function HeadlessBlockStyles\Rest\supported_post_types;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'rest_api_init', __NAMESPACE__ . '\\register_rendered_blocks_field' );
/**
 * Registers the `rendered_blocks` field on all REST-enabled post types.
 *
 * @return void
 */
function register_rendered_blocks_field() {
	register_rest_field(
		supported_post_types(),
		'rendered_blocks',
		array(
			'get_callback' => __NAMESPACE__ . '\\get_rendered_blocks',
			'schema'       => array(
				'description' => __( 'Rendered block HTML together with the block-support CSS and duotone SVG generated during the same render.', 'headless-block-styles' ),
				'type'        => 'object',
				'properties'  => array(
					'html' => array( 'type' => 'string' ),
					'css'  => array( 'type' => 'string' ),
					'svg'  => array( 'type' => 'string' ),
				),
				'context'     => array( 'view', 'edit' ),
				'readonly'    => true,
			),
		)
	);
}

/**
 * REST field callback: renders the post content and captures the
 * block-support CSS and duotone SVG emitted by that render.
 *
 * @param array $post_data Prepared post data.
 * @return array {
 *     @type string $html Rendered block HTML.
 *     @type string $css  Generated block-support CSS scoped to this render.
 *     @type string $svg  Duotone SVG filter definitions, if any.
 * }
 */
function get_rendered_blocks( array $post_data ) {
	$empty = array(
		'html' => '',
		'css'  => '',
		'svg'  => '',
	);

	$post = get_post( $post_data['id'] ?? 0 );

	if ( ! $post || post_password_required( $post ) ) {
		return $empty;
	}

	// Reset the style engine stores so the captured CSS is scoped to this
	// render, not everything rendered earlier in the request.
	if ( class_exists( '\WP_Style_Engine_CSS_Rules_Store' ) ) {
		\WP_Style_Engine_CSS_Rules_Store::remove_all_stores();
	}

	$html = do_blocks( $post->post_content );

	$svg = '';
	if ( class_exists( '\WP_Duotone' ) ) {
		// Appends the used duotone filter declarations to the block-supports
		// store so they end up in the captured CSS below.
		\WP_Duotone::output_block_styles();

		ob_start();
		\WP_Duotone::output_footer_assets();
		$svg = trim( ob_get_clean() );
	}

	$css = function_exists( 'wp_style_engine_get_stylesheet_from_context' )
		? wp_style_engine_get_stylesheet_from_context( 'block-supports' )
		: '';

	return array(
		'html' => $html,
		'css'  => $css,
		'svg'  => $svg,
	);
}
